//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.SGA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoSeccion
    {
        public int Id { get; set; }
        public int IdSeccion { get; set; }
        public int IdCurso { get; set; }
        public int IdProfesor { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
