//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.SGA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.Cursos = new HashSet<Curso>();
            this.Secciones = new HashSet<Seccion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Anio { get; set; }
    
        public virtual ICollection<Curso> Cursos { get; set; }
        public virtual ICollection<Seccion> Secciones { get; set; }
    }
}
