//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.SGA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoSeccion
    {
        public AlumnoSeccion()
        {
            this.SGA_T_ALUMNO_SECCION_CURSO = new HashSet<AlumnoSeccionCurso>();
        }
    
        public int Id { get; set; }
        public int IdAlumno { get; set; }
        public int IdSeccion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual ICollection<AlumnoSeccionCurso> SGA_T_ALUMNO_SECCION_CURSO { get; set; }
        public virtual Seccion SGA_T_SECCION { get; set; }
    }
}
