//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.SGA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_T_USUARIO
    {
        public int usu_c_iid { get; set; }
        public string usu_c_vnombres { get; set; }
        public string usu_c_vapellido_paterno { get; set; }
        public string usu_c_vapellido_materno { get; set; }
    }
}
