//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.SGA.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using NS.SGA.DomainModel;
    
    public partial class SGAEntities : DbContext
    {
        public SGAEntities()
            : base("name=SGAEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grado> Grados { get; set; }
        public virtual DbSet<Alumno> Alumnos { get; set; }
        public virtual DbSet<AlumnoSeccion> AlumnosSecciones { get; set; }
        public virtual DbSet<AlumnoSeccionCurso> AlumnosSeccionesCursos { get; set; }
        public virtual DbSet<Colegio> Colegio { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursoSeccion> CursosSecciones { get; set; }
        public virtual DbSet<Periodo> Periodos { get; set; }
        public virtual DbSet<Profesor> Profesores { get; set; }
        public virtual DbSet<Seccion> Secciones { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<SGA_T_USUARIO> SGA_T_USUARIO { get; set; }
    }
}
